const data = [
  {
    id: 1,
    owner: 'Not available',
    name: 'ACK Dioces Of Kirinyaga (OASIS)',
    desc: [
      'Situated 1000M from University',
      'A ladies ONLY hostel',
      'Four students per room',
      'Bed and mattresses provided',
      'Meals not provided',
    ],
    img: '',
    phone: '',
  },
  {
    id: 2,
    owner: 'Not available',
    name: 'Graceland',
    desc: [
      'Self-contained rooms',
      'Students can choose to stay alone r a maximum of two per room',
      'Beds,Mattresses and beddings are not provided',
      'Located 300M from the University near DEE Eight giraffe hostel',
      'Free WIFI and DSTV services',
      'Water provided at no extra charges',
      'Students to meet own electricity charges pre-paid tokens',
    ],
    img: '',
    phone: '',
  },
  {
    id: 3,
    owner: 'Not available',
    name: 'HemiChaff Hostels',
    desc: [
      '(Ladies and males ) hostels',
      'Large rooms 6000 per room per month per person and 8000 per room (2 sharing)',
      'Small rooms 4000 per room per person',
    ],
    img: '',
    phone: '',
  },
  {
    id: 4,
    owner: 'Not available',
    name: 'Executive Hostel',
    desc: [
      'Situated in Kutus 50M from the University',
      'Self contained rooms',
      'A ladies and Men hostel',
      'Four students per room',
      'Bed and mattresses provided',
      'Tables and chair provided',
      'Beddings not provided',
      'Meals not provided',
      'Free WIFI and DSTV services',
      '24 HR CCTV surviellance',
    ],
    img: '',
    phone: '',
  },
  {
    id: 5,
    owner: 'Not available',
    name: 'CLOVER',
    desc: [
      'A ladies Hostel',
      'Located about 300m from the university',
      'Students stay two per room',
      'Meals are available on pay as you eat basis',
      'Beds and matressses are provided',
      'Beddings  not provided',
    ],
    img: '',
    phone: '',
  },
  {
    id: 6,
    owner: 'Not available',
    name: 'MORY HOSTELS (BLOCKS A & B)',
    desc: [
      "Blocks A host's men and Block B hosts ladies",
      'Situated opposite Kutus kobil Petrol station, about 200m from the univeristy',
      'Two students per room',
      'Bed and mattresses are provided',
      'Beddings not provided',
    ],
    img: '',
    phone: '',
  },
  {
    id: 7,
    owner: 'Not available',
    name: 'Paradise',
    desc: [
      'Situated next to Kutus market about 1000 meters from the university',
      "Men's and ladie's hostel",
      'Four students per room',
      'Bed and mattresses provided but no beddings',
    ],
    img: '',
    phone: '',
  },
  {
    id: 8,
    owner: 'Not available',
    name: 'Early Bird Hostels',
    desc: [
      'Male and female hostel',
      'Situated 200m from kutus town next to FEB church',
      'Students can choose to stay in two or four in aroom and pay different charges as indicated',
      'Bed and mattresses provided but no beddings',
    ],
    img: '',
    phone: '',
  },
  {
    id: 9,
    owner: 'Not available',
    name: 'Elegant Hostel',
    desc: [
      'Located in kutus about 500 meters from the university',
      'A ladies and men hostel',
      'Beddings are not provided',
      'Bed and mattresses provided',
      'Chairs adn tables are provided',
    ],
    img: '',
    phone: '',
  },
  {
    id: 10,
    owner: 'Not available',
    name: 'Joslian Hostel',
    desc: [
      'Ladies and men hostel',
      'Rooms are self-contained',
      'Matresses and beddings are not provided',
      'Chairs and tables are provided',
      'Located in kutus about 300m from the university',
    ],
    img: '',
    phone: '',
  },
  {
    id: 11,
    owner: 'Not available',
    name: 'Amikas Hostel',
    desc: [
      'Situated 300m from the University',
      "A ladies and men's hostel",
      'Students stay one per room and a maximum of two in a room',
      'Bed and mattresses provided',
      'Meals not provided',
      'Beddings not provided',
    ],
    img: '',
    phone: '',
  },
  {
    id: 12,
    owner: 'Not available',
    name: 'Real Vision Hostel',
    desc: [
      'Situated in kutus Kobil station, about 300m from the university',
      'A ladies  hostel',
      'Four students per room',
      'Hot shower',
      'Bed and mattresses provided but no beddings',
      "There's a kitchen where students can prepare meals at no extra cost",
    ],
    img: '',
    phone: '',
  },
];
export default data;
